apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai4dd-demo-edit
  namespace: ai4dd-06afdc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  name: ai4dd-demo
