apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-admin-credentials
  namespace: minio
spec:
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-obs/minio/minio-admin-credentials
