---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-user-settings-reader
  namespace: default
rules:
- verbs:
  - list
  - get
  - update
  - patch
  apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - kubevirt-user-settings
