---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-ui-features-reader
  namespace: default
rules:
- verbs:
  - list
  - get
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - kubevirt-ui-features
