apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-robbie-allow-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  namespace: project-robbie-b4784c
  name: robbie-job-runner
