apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-monitoring-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - prometheusrules
      - alertmanagerconfigs
