apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-admin-credentials
  namespace: minio
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: minio-admin-credentials
  dataFrom:
    - extract:
        key: $ENV/$CLUSTER/minio/minio-config
